
# This program is built for handling exceptions.

def safe_divide(x, y)
    begin

        puts x / y

    rescue
        puts "Zero Division Error: #{e}"

    end
    
end
